[[constraint]]
  branch = "master"
  name = "github.com/dgrijalva/jwt-go"

[[constraint]]
  branch = "api-v1"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = ">=1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = ">=1.13.0"

[[override]]
  name = "github.com/lyft/protoc-gen-validate"
  version = ">=0.0.7"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = ">=1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = ">=1.0.0"

[prune]
  go-tests = true
  unused-packages = true
